### ISSUE TITLE
[BUG] Gale Winds not scaling correctly

### ISSUE THREAD

**Issue by ssabbyccatt** [JamminL/cata-classic-bugs#1013]
#### 1.1. Description
Gale Winds talent is not providing an additional 15% dmg per talent point.
  #### 1.2. How to Reproduce
           1. Note hurricane ticks without Gale Winds talent
           2. Apply Gale Winds and note new values
  #### 1.3  Source Material
With 2/2 - https://cdn.discordapp.com/attachments/1171267821112676363/1233373041782689803/image.png?ex=662cdba8&is=662b8a28&hm=6695a2feeac2a47cb00b9daa5a987e69b1253f539126e9614a13b5028492e6a8&
With 1/2 - https://cdn.discordapp.com/attachments/1171267821112676363/1233374764379275354/image.png?ex=662cdd42&is=662b8bc2&hm=3c689fb3ef3a0cd08e1883cb172dd59ddd5bdca884faab777b26ef842303fc4f&
Without GW - https://cdn.discordapp.com/attachments/1171267821112676363/1233373136892858478/image.png?ex=662cdbbe&is=662b8a3e&hm=de2725a0840f3f34f52e181c95d1363844e4c9627466cf631b5691351b25057d&
#### 2.1. Description
With 0 points, each tick does 715 damage. Expected value for 1 point is 822-823. Expected value for 2 points is 929-930. Observed values are 816-817 with 1 point and 917-918 with 2 points. It is unknown if this behavior is true to 4.3.3 or a classic only bug.
  #### 2.2 Source Material
https://www.wowhead.com/cata/spell=48514/gale-winds

**Comment by raethkcj** [comment]
While unintuitive, certain modifiers in the game have always been "additive" rather than multiplicative, and there's no indication that this is incorrect here. While it's not really documented anywhere, the general understanding is that Auras that use EffectAura types 107 and 108 in the database, displayed on Wowhead as "Apply Aura: Modifies ..." are Additive, while Auras that use EffectAura 79, like [Solar Eclipse](https://www.wowhead.com/cata/spell=48517/eclipse-solar), shown on Wowhead as "Apply Aura: Mod ..." are Multiplicative.

Presumably you're talented into [3/3 Genesis](https://www.wowhead.com/cata/spell=57812/genesis), which is Additive, which means your Hurricane is already buffed by 6%. Since Gale Winds is also Additive, the total combined effect of the two auras will be `6% + 15% = 21%` for 1 point or `6% + 30% = 36%` for two points. To see the *relative* increase while already having one Additive aura active, you could multiply by the new total divided by the current total: `715 * 1.21 / 1.06 = 816` for one point, or `715 * 1.36 / 1.06 = 917` for two points.

The reason it may sometimes look multiplicative with other things, as you mentioned in #1014, is that after Additive modifiers are all summed up, the sum then acts as one lump Multiplicative modifier.

So with just Genesis and zero-mastery Solar Eclipse, we'd get `Base * (1 + 0.06) * (1 * 0.25)`, which is no different than if both were multiplicative. Whereas if we add in Gale Winds, we'd get `Base * (1 + 0.06 + 0.30) * (1 + 0.25)`. So you always need more than one Additive modifier for the Additive vs Multiplicative situation to make a difference in the end result.

Hopefully that clears things up.

**Comment by ssabbyccatt** [comment]
> While unintuitive, certain modifiers in the game have always been "additive" rather than multiplicative, and there's no indication that this is incorrect here. While it's not really documented anywhere, the general understanding is that Auras that use EffectAura types 107 and 108 in the database, displayed on Wowhead as "Apply Aura: Modifies ..." are Additive, while Auras that use EffectAura 79, like [Solar Eclipse](https://www.wowhead.com/cata/spell=48517/eclipse-solar), shown on Wowhead as "Apply Aura: Mod ..." are Multiplicative.
> 
> Presumably you're talented into [3/3 Genesis](https://www.wowhead.com/cata/spell=57812/genesis), which is Additive, which means your Hurricane is already buffed by 6%. Since Gale Winds is also Additive, the total combined effect of the two auras will be `6% + 15% = 21%` for 1 point or `6% + 30% = 36%` for two points. To see the _relative_ increase while already having one Additive aura active, you could multiply by the new total divided by the current total: `715 * 1.21 / 1.06 = 816` for one point, or `715 * 1.36 / 1.06 = 917` for two points.
> 
> The reason it may sometimes look multiplicative with other things, as you mentioned in #1014, is that after Additive modifiers are all summed up, the sum then acts as one lump Multiplicative modifier.
> 
> So with just Genesis and zero-mastery Solar Eclipse, we'd get `Base * (1 + 0.06) * (1 * 0.25)`, which is no different than if both were multiplicative. Whereas if we add in Gale Winds, we'd get `Base * (1 + 0.06 + 0.30) * (1 + 0.25)`. So you always need more than one Additive modifier for the Additive vs Multiplicative situation to make a difference in the end result.
> 
> Hopefully that clears things up.

Works for me, ty for looking into it and getting back to us.
