### ISSUE TITLE
[BUG] Frostfire Orb

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1020]
#### 1.1. Description
Frostfire Orb isn't slowing when hitting someone, and the animation is bugged
  #### 1.2. How to Reproduce
           1. Frostfire orb someone in the directon of an enemy
           2. Watch as it hits the enemy but runs past it
  #### 1.3  Source Material

https://github.com/JamminL/cata-classic-bugs/assets/107503518/cb508c93-b758-4e83-909a-7274a0ceed53

**Comment by Rivahlol** [comment]
Very big issue for mages, the orb keeps going in a straight line and does not stop when hitting an enemy. Still bugued on the beta.

**Comment by laynerzy** [comment]
Also applies to flame orb, frost mage is unplayable atm

**Comment by Rivahlol** [comment]
Small upgrade here, still bugued, it's frost mages best ability and right now it's not playable.

**Comment by AidanZMoon** [comment]
Team is aware. There are 4 bugs with it before we ship a fix.

1. It isn't slowing itself when it deals damage.
2. The beams spawn from the ground and not the middle of the orb.
3. When talented into frostfire orb it has an extra visual that is large, and higher than the flame orb.
4. When the orb expires it flops to the ground as if it has a death animation instead of fading out.

All 4 fixes will be shipped together so there will not be a fix until all 4 are completed.

**Comment by Rivahlol** [comment]
> Team is aware. There are 4 bugs with it before we ship a fix.
> 
> 1. It isn't slowing itself when it deals damage.
> 2. The beams spawn from the ground and not the middle of the orb.
> 3. When talented into frostfire orb it has an extra visual that is large, and higher than the flame orb.
> 4. When the orb expires it flops to the ground as if it has a death animation instead of fading out.
> 
> All 4 fixes will be shipped together so there will not be a fix until all 4 are completed.

Thank you very much for the update, hope it'll get fixed soon, frost mage is such a popular and fun spec :D
