### ISSUE TITLE
[BUG] Hunter Traps Arming Timer is bugged.

### ISSUE THREAD

**Issue by Kenniflopper** [JamminL/cata-classic-bugs#1041]
#### 1.1. Description
Currently Hunter Trap's Arming time is completely RNG, it does not have a static arming timer as it should have in Cataclysm.
  #### 1.2. How to Reproduce
       Use Freezing / Snake Trap on an enemy Target with trap launcher and notice how RNG the arming timer is, ranging between 1-4seconds.
  #### 1.3  Source Material
1. https://youtu.be/7NiwXyMzI1o
2. https://youtu.be/liWrAOiDA40
3. https://youtu.be/Phwc1UMsYrE
4. https://youtu.be/fp0aquW0uKE
5. https://youtu.be/I_lPnaYK2Z0
#### 2.1. Description
Hunter traps were supposed to have a Static Arming Timer of 1 second in Cataclysm. Which was sometimes abit longer due to the Tickrate/ Spell Batching back in original Cataclysm but traps almost never exceeded the 2 Second Mark.
  #### 2.2 Source Material
https://wowwiki-archive.fandom.com/wiki/Freezing_Trap
https://wowwiki-archive.fandom.com/wiki/Trap
Trap 1-  https://youtube.com/clip/UgkxVNZb9c9M4KoxtYvSeRRBg-hAR4LBzRM3?si=moaniuidu39dzU_Z
Trap 2 - https://youtube.com/clip/UgkxbVvUvspuGxhlWKs9KZwVaIXPfnScaYMs?si=roLIjpGcdBg35wDv
Trap 3 - https://youtube.com/clip/UgkxzgucD53-_4OauDHTsn4eyTitz33ndsZQ?si=7c9kG7EgKPjLSkJT
Trap 4 - https://youtube.com/clip/Ugkx2gcu06YSjFgPm3OD6zlrvacjnLiWv24U?si=mEg-VCWawJ4aCQBo
Trap 5 - https://youtube.com/clip/Ugkxy1nobiCXZHgdkghanWZI6xE3pyjKtW42?si=-4AfniuHYNSD9q2r
Trap 6 - https://youtube.com/clip/UgkxVmAsR1RVMtVE_8uS3tWJBlsbRgYXZweG?si=N0EtW9x6agO3TaXW
Trap 7 - https://youtube.com/clip/Ugkx8yFTxNocEixIRdikR4dL6JpzxCNS6Pao?si=0-PkpMU4dgHvrI84
FULL VIDEO as referance  - https://www.youtube.com/watch?v=b1jk5nxa2nU
FULL VIDEO as referance - https://www.youtube.com/watch?v=uxYgZMaR9zU

**Comment by skinnay-dev** [comment]
A couple logs I did for arming time testing:
https://classic.warcraftlogs.com/reports/CR4df1BTLZcFHVJy#fight=1&view=events&type=summary&pins=2%24Off%24%23244F4B%24expression%24ability.id%20%3D%20%221499%22%20or%20ability.id%20%3D%20%2260192%22%20or%20ability.id%20%3D%20%223355%22

https://classic.warcraftlogs.com/reports/M9ZR7kqHtV4xK8Cj#fight=1&view=events&pins=2%24Off%24%23244F4B%24expression%24ability.id%20%3D%20%221499%22%20or%20ability.id%20%3D%20%2260192%22%20or%20ability.id%20%3D%20%223355%22

**Comment by ManneN1** [comment]
Incredibly important to fix this. Incredibly important. This is make it or break it for the entire class - and has been the primary reason Hunter has not been effective at all in WotLK.

**Comment by MannySJH** [comment]
I imagine something like this would be unlikely to be fixed as it was a complex issue in wrath too. Seems like instant arming traps in retail (maybe sod too) completely negate this issue. Obviously these don't belong in these old expansions where enemy players are often trying to deny trapping crowd control with ground or purposely taking the trap intended for others etc. I wonder if it would be possible to remove the arming time from launched traps but artificially add the intended arm time (1s) to the travel time of the trap at all distances instead. This would essentially keep the counter play mechanics the same while making trapping players incredibly consistent. Unfortunately this wouldn't work for placed traps, these would have to stay the same with the old bugged arming time but even with this it would be a massive positive for hunters in arena.

**Comment by ManneN1** [comment]
> I imagine something like this would be unlikely to be fixed as it was a complex issue in wrath too. Seems like instant arming traps in retail (maybe sod too) completely negate this issue. Obviously these don't belong in these old expansions where enemy players are often trying to deny trapping crowd control with ground or purposely taking the trap intended for others etc. I wonder if it would be possible to remove the arming time from launched traps but artificially add the intended arm time (1s) to the travel time of the trap at all distances instead. This would essentially keep the counter play mechanics the same while making trapping players incredibly consistent.

Sounds like a great solution. Would need to add some kind of fake animation to indicate where the trap will land (so people can try to take it for their teammates), but other than that it's a great solution.

Honestly, the fake animation could even be the trap flying at its normal "old" pace and then looking as if it's arming just like normal, and the new real "slow" trap could be completely hidden (until it spawns the trap object and everything is the same). That way, visually and functionally, it would be exactly the same as before to the end user (just under the hood the actual trap would be in the air still while players believe, due to the fake animation, that it has already landed and is arming).

> Unfortunately this wouldn't work for placed traps, these would have to stay the same with the old bugged arming time but even with this it would be a massive positive for hunters in arena.

As far as I understand the thing that is causing the inconsistency is that spawned objects (in this case traps) are very inconsistent with either the arming time or the activation check (seemingly it's the arming time since it's consistent in SoD where there's no arming time):

If that's the case, there's a fix for this as well.

In case it's the arming time that's inconsistent:

One could change the behaviour of the placed non-launcher trap spells. Keep the same animation (bend down and place trap) as currently but instead of placing a trap object have them cast an location based aura (right where the trap object would've been, with a fake animation that looks like the trap arming) that activates after 1 second and which then spawns the trap object (the trap object would in this case need to have the arming time entirely removed, similar to what was already proposed).

In case the issue instead lies with the activation check for objects itself being inconsistent the activation aura would upon expiration (1sec) need to either:
- if someone is in the trigger area that would activate the "trap": Instantly apply the auras the trap would've applied to the correct target / area (and play a fake animation indicating that the "trap" was activated).
- if no one is in the trigger area: place the trap object like normal (this would leave the bug remaining only in the niche case where someone walks out of your placed trap during the 1sec location aura "trigger" window and then walks back into it when the real trap object is spawned, and then walks out of it again because of it not activating consistently).

**Comment by MannySJH** [comment]
> Sounds like a great solution. Would need to add some kind of fake animation to indicate where the trap will land (so people can try to take it for their teammates), but other than that it's a great solution.

I Imagine something as simple as a miniature ring of frost decal on the floor would suffice for this, maybe blue to indicate frost, green to indicate snake and red to indicate fire

**Comment by ManneN1** [comment]
> > Sounds like a great solution. Would need to add some kind of fake animation to indicate where the trap will land (so people can try to take it for their teammates), but other than that it's a great solution.
> 
> I Imagine something as simple as a miniature ring of frost decal on the floor would suffice for this, maybe blue to indicate frost, green to indicate snake and red to indicate fire

Yeah, it's all effort level on this one.

**Comment by Heroclassx** [comment]
Not sure if this is 100% the correct topic for this but we had some bug occur yesterday regarding trap trigger/arm time aswell.

https://www.twitch.tv/medalxz/clip/HappyCallousHerringWOOP-9ElugYRXs36oP5GC?filter=clips&range=7d&sort=time
This was on beta
