### ISSUE TITLE
[BUG] Smoke Bomb doesn't remove Stealth

### ISSUE THREAD

**Issue by Avizurax7** [JamminL/cata-classic-bugs#1042]
#### 1.1. Description
Currently on the Classic cata BETA when you go inside a smoke bomb of an enemy rogue, it does not take you out of stealth or similiar effects. Although this should not affect Vanish because of the vanish buff that last 3 seconds, please make sure that stays as it is intended.
  #### 1.2. How to Reproduce
         1. Have an enemy rogue use smoke bomb
         2. Stand inside the smoke bomb OR walk inside of it while stealthed.
         3. Notice how it doesn't take you out of stealth.
  #### 1.3  Source Material
https://streamable.com/j5v4sp
#### 2.1. Description
It should remove stealth/prowl/shadowmeld when walking inside an ENEMY rogue's Smoke Bomb.
  #### 2.2 Source Material
https://youtu.be/EmtPGXtugMg?si=bLQ4h1FbbH0VrwO7&t=266 (if timestamp doesn't work for some reason, go to 4:26 minutes).

**Comment by ManneN1** [comment]
@Aggrend this is similar to [this issue](https://github.com/JamminL/cata-classic-bugs/issues/1172). It's most likely not an actual intended behaviour, but a bug (that happened to stay in the game due to time/technical issues) because it was fixed in early MoP along with Spirit Link Totem starting to redistribute HP to targets within the link. See [this issue](https://github.com/JamminL/cata-classic-bugs/issues/1397) for more details.

If you want to stay **consistent** with your logic, this should be considered _Not a Bug_ (unintended behaviour) and the "fix" that you did for this in beta should be undone (most likely due to time crunch and not being informed to second guess this info).
