### ISSUE TITLE
[BUG] 'the Bloodthirsty' 250.000 honorable kills reward title missing

### ISSUE THREAD

**Issue by lavjamanxd** [JamminL/cata-classic-bugs#1099]
#### 1.1. Description
Simple as that 250k honorable kills done, achivement completed, no title. I got other titles since cata released so i'm pretty sure that not the titles bugged at all, only this one.
  #### 1.2. How to Reproduce
1. Farm 250k players (lol)
2. No title
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/10040415/06fc519d-09f1-41eb-82e5-a192b27ff6b5)
![image](https://github.com/JamminL/cata-classic-bugs/assets/10040415/0f12bc21-c0eb-4605-943e-8ef18ac6586d)
![image](https://github.com/JamminL/cata-classic-bugs/assets/10040415/86fd2666-5ee1-4da7-906d-7a743b62bd16)
### 2. Expected Behavior
The achievement gives the title to my character.

**Comment by LordOfOtakus** [comment]
This issue seems to affect any titles granted by achievements that track progress across all characters, if you hadn’t completed them prior to pre-patch. This is also very likely related or caused by the same issue that is preventing titles from account-wide achievements being granted to all characters.

**Comment by LordOfOtakus** [comment]
A hotfix for this appears to have hit servers as of 10:21 PM EST.
