### ISSUE TITLE
[BUG] Performance stutters associated with items on actionbars 

### ISSUE THREAD

**Issue by MannySJH** [JamminL/cata-classic-bugs#1107]
#### 1.2. How to Reproduce
          
           1. Smooth game play when action bars are completely empty
           2. Add weapons/items to the bars
           3. Observe performance decrease
  #### 1.3  Source Material
https://streamable.com/8n221a
Original post : https://www.reddit.com/r/classicwow/comments/1chsau3/game_stutteringgetting_minifreezes_after_cata/

**Comment by ssabbyccatt** [comment]
![Screenshot 2024-05-02 234311](https://github.com/JamminL/cata-classic-bugs/assets/99249505/cc18a780-6eca-45d1-8a1f-ce5237bae7f8)
just providing additional documentation that this is occurring, reported in druid discord

**Comment by MannySJH** [comment]
Noticed a heavy stutter a few days ago related to complex pet macros especially when they are spammed rapidly. I gave up until I found out about the above issue also. Turns out spamming a complex pet macro will have a slight effect on performance (almost negligible) as you can see from the video attached. However when you combine these two things together the result is catastrophic and unplayable.

https://streamable.com/u01tcq

**Comment by infrex** [comment]
From the 10 people I've asked to replicate this, 50% of the people were successful.
It gets especially bad with a mouseover macro, such as /use [@mouseover] 10

**Comment by Dayliex** [comment]
Can confirm. My friend had gloves (because of engineering on-use ability) and trinket = he had insane stuttering
After he removed gloves and trinket from bars, no more stutters

For me I have same issue, but I can't simply fix it by removing items, because all my items are used through macros. PvP trinket, drinking water, using healthstone...

It goes especially bad when I play arena with a warlock and he gives me healthstone in arena.

**Comment by Calzeru** [comment]
Cata beta client just got updated to 4.4.0.54558 and the problem seems to be fixed there.
