### ISSUE TITLE
[BUG] Sated debuff not disappearing off pets after encounter ends

### ISSUE THREAD

**Issue by NoCement** [JamminL/cata-classic-bugs#1190]
#### 1.1. Description

Currently, after encounter ends, it cleanses Sated debuff from all player characters. Pets are excluded. 

  #### 1.2. How to Reproduce

           1. Pull boss, use Bloodlust/Heroism
           2. End encounter, check that Sated debuff is no longer present on player characters but it stays on pets (and minions)
           
  #### 1.3  Source Material
  
  Ingame, logs....
  
### 2. Expected Behavior

I assume it should be same as Classic Wrath where pets had to be fixed as well

  #### 2.2 Source Material

Previous fix for Wrath

**Comment by MannySJH** [comment]
Wanted to add to this since it's closely related, Call of the wild 
https://www.wowhead.com/cata/spell=53434/call-of-the-wild
A substantial pet cool down is also not being reset on wipe or encounter end. This was broken once again some time in the middle of the last phase of wrath after being fixed earlier.
