### ISSUE TITLE
[BUG] Combust is currently benefitting from mastery (Double Dipping)

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1234]
#### 1.1. Description
Combust is currently double dipping on mastery. Ignite is already affected by flashburn, and combust will then be increased again.
  #### 1.2. How to Reproduce
           1. Proc Ignite, notice how much the tick is doing (e.g 2438)
           2. Press Combust
           3. Notice how much each combust tick is doing (e.g 1768)
           4. Notice how Ignite Tick / 2 will not equal combust tick (e.g 2438 /2 != 1768)
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/107503518/05da6a9d-5302-467e-9079-ea7fe43fd8a4)
#### 2.1. Description
Combust should not benefit from mastery, as the dots already benefit
  #### 2.2 Source Material
4.2 Hotfix: Combustion damage from Ignite is no longer penalized by Resilience more than once, nor can it gain double benefit from Flashburn (mastery).

**Comment by gjoeyjoe** [comment]
Just adding some more proof/context here since we did testing in mage discord.

**The following is the calculations done at time of pressing combust, assuming the dot is active**
```
Living Bomb: (floor(0.25 * 937.3) + 0.258 * SpellPower) * 1.25 Spec Bonus * 1.03 Fire Power * Mastery * CriticalMass
Pyroblast: (floor(0.175 * 973.3) + 0.180 * SpellPower) * 1.25 * 1.03 * Mastery
Ignite (numTicks = 2 for fresh, 3 for refresh): IgniteBank * floor(Mastery) / numTicks / 2
```

As you can see, LB and Pyroblast only use Mastery once, which is intuitive to Combust. 
Ignite gets multiplied by Mastery rounded down (so 22.4% -> 22%).

Side note, but Living Bomb's DoT is calculated with Critical Mass additive with Mastery, while Living Bomb's contribution to Combustion is calculated with Critical Mass multiplicative. For intuition's sake, it'd make sense to match them, but that's just a suggestion. 
![image](https://github.com/JamminL/cata-classic-bugs/assets/56170044/8028dc95-436a-456a-951f-bcbc023c9d17)

**Comment by gjoeyjoe** [comment]
Looking more into this, if this is due to a 4.2 change to resilience, this would go along with the theory that Ignite did not double-dip based on 4.0 cata EJ threads (https://web.archive.org/web/20110226111242/http://elitistjerks.com/f75/t110187-cataclysm_mage_simulators_formulators/p3/#post1824829). 

However, this thread also theorizes that Living Bomb and Pyroblast _would_ double-dip on mastery. In the formulas for LB and Pyro in my previous comment, you would again multiply by Mastery.
