### ISSUE TITLE
[BUG] Warlock Spell Burning Embers is not scaling with Mastery

### ISSUE THREAD

**Issue by dreschnuutest** [JamminL/cata-classic-bugs#1266]
#### 1.1. Description
Destruction Warlocks spell Burning Embers is currently not scaling with Mastery.
Mastery is supposed to increase all fire damage by X%.
  #### 1.2. How to Reproduce
          Describe the steps to reproduce the particular bug, in detail:
           1. Specc into Burning Embers
           2. Equip Full Mastery
           3. Cast Soul Fire
           4. Reforge Mastery to something else
           5. Cast Soul fire
           6. Watch the damage of the DoT be the same.
         
  #### 2.1. Description
Mastery should increase the dmg of the DoT by X%

**Comment by AidanZMoon** [comment]
This is not a bug and matches 4.3.4 Reference Cataclysm.

The reason for this is 2 fold.
1. Burning Embers has a cap on its damage stated on the tooltip where it says it deals damage "up to" a certain amount. You cannot exceed that cap, and that cap is based on spell power, and does not increased with Mastery. The cap is also to make it so Crit Soulfires don't benefit this DoT to an extreme amount.
2. Burning Embers also does not DIRECTLY benefit from Mastery because it INDIRECTLY does, and would be Double Dipping if it factored Mastery into the DoT itself, effectively applying Mastery a second time. The reason for this is Burning Embers is already based on 50% of the damage of Soul Fire, and Soul Fire is increased by Mastery.

So if I hit a Soul Fire for 100 damage my Burning Embers will deal 50% of that damage, 50 damage total.
Then if I equip 70% mastery, my Soul Fire will deal 170 damage and my burning embers will deal 50% of that damage, 85 damage total.
Increased by Mastery Soul Fire's damage divided by Previous Sol Fire's damage -> 85 divided by 50 is 1.70. So your Burning Embers would've increased by 70% if your Soul Fire's damage increased by 70%, if it wasn't for the cap.
Otherwise you'd run into situations where it would deal 85 damage, an increase of 70% from the 50 it dealt before, and then get increased by 70% again.
