### ISSUE TITLE
[BUG] [WARRIOR] Throwdown doesn't apply knockdown, only the stun

### ISSUE THREAD

**Issue by Azmoddan** [JamminL/cata-classic-bugs#1358]
#### 1.1. Description
(https://www.wowhead.com/cata/spell=85388)
Currently only stuns the target for 5 seconds. If removed at any point, you can instantly start moving again.
  #### 1.2. How to Reproduce

           1. Log warrior
           2. Throwdown a player
           3. Player trinkets Throwdown and is able to move instantly
#### 2.1. Description
On top of a 5 second stun, the spell is supposed to apply knockdown mechanic for the duration of the knockdown animation (around 1-1.5s). If debuff is removed early, whether through PvP trinket or other means, they are not supposed to be able to move until (at least) knockdown animation is over.
  #### 2.2 Source Material
  Wowhead comment from the link above:
![image](https://github.com/JamminL/cata-classic-bugs/assets/42694757/d1dbc3de-1366-44af-8ffe-c316e24311c0)

  Klinda 11 (patch 4.3+)
(https://youtu.be/6zyrTlaDs-E?si=9-CeRXyqUr6gNubB&t=163)
the priest trinkets before the knockdown animation ends, he can't move until the animation is over.
https://youtu.be/6zyrTlaDs-E?si=ZJxddw3d6O248-3K&t=481
warrior can't move for a bit after trinketting throwdown, for even slightly longer than the knockdown animation
https://youtu.be/6zyrTlaDs-E?si=if1YoRtqh2LaOWTZ&t=685
death knight pressed icebound fortitude to remove throwdown, unable to move for quite some time after

Different video, paladin trinkets before knockdown effect is over, can't move the character
https://youtu.be/qiao9OUKHZI?si=E0L0vkFCv02ChpWe&t=399

Every video posted above has been uploaded before the release of Mists of Pandaria. Inb4 someone says I cherry picked the clips, just type this in YouTube search engine and sort by newest for more pre-mop warrior videos.
![image](https://github.com/JamminL/cata-classic-bugs/assets/42694757/ecd8a78d-1c8c-4741-a84c-4a545ba365e6)

Think the ability should get fixed, because:
- it's expansion specific, gets completely removed in Mists of Pandaria and is replaced by Storm Bolt
- doesn't work as intended

**Comment by AidanZMoon** [comment]
I have been noticing some odd behaviors around kncok downs in general.
I remember some boss or quest knocked me down but I could still move the entire time.

May be a larger issue with knock down effects. Would check Earthquake as well.

**Comment by Azmoddan** [comment]
> I have been noticing some odd behaviors around kncok downs in general. I remember some boss or quest knocked me down but I could still move the entire time.
> 
> May be a larger issue with knock down effects. Would check Earthquake as well.

I vaguely remember questing as a human, being knockdown by different mobs & trinketting with racial, sometimes I could move, sometimes I couldn't - as if there was a hidden flag behind some knockdown-type spells but not the others.

**Comment by AidanZMoon** [comment]
Yeah, I've definitely had the - trinket the stun, slide around in a knockdown animation but in full control experience somewhere.

**Comment by dreschnuutest** [comment]
Surely it was intended to not be trinketable for the first 1.5sec lets be real here now

**Comment by AidanZMoon** [comment]
Did some research on this - For context, we have access to all of the original tickets from previous expansions and I found a ticket with notes/a conversation during Cataclysm about how this is 100% bugged behavior.

There was never an intended "Knockdown" effect on any ability. There isn't even a category for crowd control called Knockdown or anything. These were always "Apply Aura Stuns," just like Kidney Shot, that SOMETIMES had a different animation for flavor. These animations though, had issues.

The animation system did not have a way to abort knockdown animations early, and it would lock the player out of their movement until their animation finished, even if their Stun Aura had been removed.

This was deemed a bug during Cataclysm's original life cycle but a fix was not seen until 5.0.1 due to the undertaking.

So in its current form on 4.4.0 - this is NOT working as it was experienced back then, but it IS working how it was intended.

Bonus info:
Because of the bug back in the day - Knockdown had wildly variant results when trinketed based on the time to completion of the player's Knockdown animation. So some races/forms were worse against this when trinketing it at the start of the ability. Or in the case of something like a Feral Druid in Cat Form - they practically had no knockdown animation - so Cats recovered almost instantly.
