### ISSUE TITLE
[BUG] Binding of the Ice Burrower too much stats

### ISSUE THREAD

**Issue by JustForYou24** [JamminL/cata-classic-bugs#707]
#### 1.1. Description
Binding of the Ice Burrower  -  https://www.wowhead.com/wotlk/item=47426/binding-of-the-ice-burrower has too much stats
you can compare it to Girdle of the Forgotten Martyr = https://www.wowhead.com/wotlk/item=47484/girdle-of-the-forgotten-martyr  
+ 10 spell power
+8 crit

**Comment by where-fore** [comment]
For whatever it's worth, [this old database](https://wowclassicdb.com/wotlk/item/47426) corroborates that there are too many stats on live, this version has the proposed -10 Spell Power and -8 Crit, same as the plate alternative.

**Comment by JamminL** [comment]
> For whatever it's worth, [this old database](https://wowclassicdb.com/wotlk/item/47426) corroborates that there are too many stats on live, this version has the proposed -10 Spell Power and -8 Crit, same as the plate alternative.

The issue is in original wrath, the horde and alliance versions had different stats. When it was adjusted in classic, they both had the higher version of those stats. However, judging by the ilvl increase and other items of similar stats, it was clear the "correct" version was the faction version with the lower stats.
