### ISSUE TITLE
[BUG] Worgen Race - Show Helm doesn't work properly.

### ISSUE THREAD

**Issue by Riastv** [JamminL/cata-classic-bugs#889]
#### Helm does not show in worgen form

**Comment by CharWS** [comment]
do you have any more information on this, which helm(s) did you check, is it particular to one worgen face/body type?

**Comment by Riastv** [comment]
It was just male worgen, I couldn't tell you the face or body type I'm sorry.

Sent via the Samsung Galaxy S20 FE 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TamerLee** [comment]
I can confirm that all helms do not appear on female worgen either, including using the dressing room for previews.

**Comment by lordblackadder** [comment]
fixed in build 54339, helms now show both on the dressing room and on the character (male & female)
![image](https://github.com/JamminL/cata-classic-bugs/assets/12127284/6d02274e-01f4-4346-aada-124505e5d69c)
![image](https://github.com/JamminL/cata-classic-bugs/assets/12127284/d0bdef04-352e-47a0-ad11-4e5c1b10d8a5)
