### ISSUE TITLE
[BUG] Death Strike only healing for minimum value

### ISSUE THREAD

**Issue by CharWS** [JamminL/cata-classic-bugs#902]
#### 1.1. Description
Currently Death Strike only heals for its minimum value of 7% of player health
  #### 1.2. How to Reproduce
           1. Use Death Strike while having taken no damage over the last 5 seconds
           2. Take a large amount of damage
           3. Use death strike within 5s of taking that damage
  #### 1.3  Source Material
https://cdn.discordapp.com/attachments/364459574327246851/1223100984369217626/image.png?ex=6618a08e&is=66062b8e&hm=2dfb587b4bd7e2aed8157e414f0e29955a0915806f7293685bdf8f7d7ba9e980& here can see that despite taking 30,268 damage over 5s the first death strike only heals for 3,163, the second death strike is cast after having taken 38,916 damage over 5s, both heal for the same amount as when no damage has been taken over the last 5s
#### 2.1. Description
Death Strike should heal for whichever value is higher between 7% of max player hp or 20% of the damage taken over the last 5s

**Comment by lordblackadder** [comment]
Appears to be fixed in build 54137

https://classic.warcraftlogs.com/reports/a:m6LMVzxjFK3GBAWg#fight=2&type=damage-taken&view=events&pins=0%24Separate%24%23244F4B%24healing%24-1%240.0.0.Any%242977659.0.0.DeathKnight%24true%240.0.0.Any%24true%240

The heal is expected to be 29% of the damage taken when talented for 45% extra healing

`39981 * 0.29 = 11565.49` same as the first DS
then 
`72891 * 0.29 = 21138` same as second DS
