### ISSUE TITLE
PvP Gearing Time Frame

### ISSUE THREAD

**Issue by Kenniflopper** [JamminL/cata-classic-bugs#951]
PVP Gearing Issues in Cataclysm:

### **_Conquest Problem_**

- Average cost for full PvP gear: 30-34k conquest points.
- Max cap of 3k extends gearing time to 10+ weeks.
- Majority of players have a 2k cap, necessitating 15+ weeks for full gear.
- Additional factors like missed weeks or alts further delay gear acquisition.
- Minimum time to full gear: 3 months; worst-case scenario: almost 4 months.
- Cataclysm Classic's one-year duration closely aligns with gear acquisition time.

**Solution:**

- Increase base conquest earned (e.g., double from 1650 to 3300).
- Implement a 'conquest catchup mechanic' for missed weeks or alt characters.

### **_Honor Problem_**

- Full honor set cost: approximately 27k Honor, including shoulder and helm resilience enchants.
- Daily BG win rewards: initially 380-400 honor, later dropping to 230-250.
- Around 90-100 BG wins required for full Honor gear, not accounting for losses.

**Solution:**

- Buff honor rate gain by 2x-2.5x to align with Cataclysm Classic's shorter seasons.

**Comment by Thegodofdmg** [comment]
^ this 1000%

**Comment by JamminL** [comment]
To add to this, the catchup mechanic that exists on retail would be ideal for cata. Due to short seasons the increased cap is not enough.

On retail, you won't lose conquest caps from past weeks so for example, if you level up an alt on week 3 and the minimum conquest cap is 1650, your cap the first week will be 4950.

This way, you don't miss out on gear progression so long as you play the necessary games to catch up, which is a win-win.

**Comment by tempestxgg** [comment]
> To add to this, the catchup mechanic that exists on retail would be ideal for cata. Due to short seasons the increased cap is not enough.
> 
> On retail, you won't lose conquest caps from past weeks so for example, if you level up an alt on week 3 and the minimum conquest cap is 1650, your cap the first week will be 4950.
> 
> This way, you don't miss out on gear progression so long as you play the necessary games to catch up, which is a win-win.

This would be ideal, good suggestion.
