### ISSUE TITLE
Remove Engineering fail chance [#SomeChanges Suggestion]

### ISSUE THREAD

**Issue by zenots** [JamminL/cata-classic-bugs#997]
As an opposite suggestion than the person wanting the fail rate to be increased, I'd suggest the fail rate should be removed in raids just like we did for WotLKC. The belt enchants are such a minor part of the profession to begin with, but adding a random chance to just die in raid instead of gain an 18k absorb or nitros, just seems like bad gameplay.

They're unusable in PvP, and are in no way game breaking for PvE outside of making it slightly more reliably for very niche groups that speedrun. I wouldn't even see any issue with the fail rate remaining in dungeons and other PvE content, just removed for raids.

**Comment by raethkcj** [comment]
Synapse Springs are already significantly better than the static bonuses provided by other professions when aligned with percent damage or percent haste increases. On top of that, engineers have access to explosives.

It's been a "mandatory" profession four Classic expansions in a row. It doesn't need a buff. Raid encounters are designed to be doable without rocket boots, and having a failure rate on something far beyond what other professions get is the only thing keeping it semi-balanced.

**Comment by NerdEgghead** [comment]
It's not a question of the profession needing the buff, it's that the Cataclysm "solution" for balancing it is a terrible one that (a) does not in any way change how "mandatory" Engineering is for competitive PvE, and instead (b) simply adds feelsbad moments for your raid team when you happen to roll the very low failure chance. If the design goal is to nerf Engineering for PvE, then the correct solution would be to make Nitro Boosts not work at all in raids. Otherwise the failure chance should be removed, since this interaction does not add _any_ fun to anyone, and simply a net negative for the playerbase as a whole, since Engineering will still be commonplace and there's now just extra rng added to the raid experience that does not need to exist.

**Comment by zenots** [comment]
> It's not a question of the profession needing a buff, it's that the Cataclysm "solution" for balancing it is a terrible one that (a) does not in any way change how "mandatory" Engineering is for competitive PvE, and instead (b) simply adds feelsbad moments for your raid team when you happen to roll the very low failure chance. If the design goal is to nerf Engineering for PvE, then the correct solution would be to make Nitro Boosts not work at all in raids. Otherwise the failure chance should be removed, since this interaction does not add _any_ fun to anyone. It is simply a net negative for the playerbase as a whole, since Engineering will still be commonplace and there's now just extra rng added to the raid experience that does not need to exist.

Not even "feels bad" but because the launch fail is still in the game it actually causes instant raid wipes on certain encounters.

**Comment by raethkcj** [comment]
I have no opposition to disabling them entirely in raids!

Alternatively:
* Remove failure, but also apply a slightly weaker DoT 100% of the time (a la Skull of Impending Doom)
* Remove failure, but weaken Synapse Springs to compensate
